stages:
  - deploy

update-deployment:
  stage: deploy
  rules:
    - if: '$DEPLOY && $DEPLOY == "TRUE" && $CI_COMMIT_BRANCH == "main"'
  image: 10.10.10.91:5000/ubuntu:16.04
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - printenv >> .env
  script:
    - echo "Adding target machine private key..."
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - echo "Updating deployment..."
    - scp -o "StrictHostKeyChecking=no" .env osuser@10.10.10.78:git/openproject-webhook/
    - >
      ssh -o StrictHostKeyChecking=no osuser@10.10.10.78 "cd git/openproject-webhook/ && git stash && git checkout main &&
      git pull && ls -a && docker-compose down && docker-compose up -d --build"
